add debug

diff --git a/.github/workflows/backend-integration-tests.yml b/.github/workflows/backend-integration-tests.yml
--- a/.github/workflows/backend-integration-tests.yml
+++ b/.github/workflows/backend-integration-tests.yml
@@ -33,6 +33,11 @@ jobs:
           path: |
             ~/.gradle/caches
             ~/.gradle/wrapper
+      - name: Debug Docker
+        run: |
+          whoami
+          docker version || echo "Docker not found"
+          ls -la /var/run/docker.sock || echo "No Docker socket"
       - name: Run Integration tests
         run: ./gradlew test -PintegrationTest --no-daemon
 
